image: node:8.4.0

before_script: 
    - cd ./backend
    - npm install
    - cd ../frontend
    - npm install
    - cd ..

cache: 
    paths:
        - backend/node_modules/
        - frontend/node_modules/
        
        
stages:
  - test_backend

job_name:
  stage: test_backend
  script:
    - cd ./backend
    - npm run test
    - cd ..
    